### ISSUE TITLE
HTML Report layout

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/CCISS_ShinyApp_v12#13]
1. Site location map. See comments in PDF layout around preseleted points
2. List of site series selected hyperlinked to section in report
For each site series selected
2. Feasibility reports showing only feasible
3. BEC futures
4. Stocking Standards
Then after all site series:
Session parameters
CCISS model info
Appendix of Silvics/Ecology for only feasible species

**Comment by kdaust** [comment]
I think this is done - will probably need some more tweaking though
