### ISSUE TITLE
All databases point to the same host.

### ISSUE THREAD

**Issue by meztez** [FLNRO-Smithers-Research/CCISS_ShinyApp_v12#23]
https://github.com/FLNRO-Smithers-Research/CCISS_ShinyApp_v12/blob/f0c5daeef1929a77271affd056768720666d66a5/app/index.Rmd#L39

The tool is creating three connection pool to three different databases, all hosted on the same server.
It would be cleaner to instead create three different schemas under the same database, so we only deal with a single connection pool.

Any particular reason to use three pool?

**Comment by meztez** [comment]
@kdaust I would not say that performance suffer that much. It consumes a tad more memory, true. Around 10Mb more. But this is not the main culprit.

The real reason is performance optimization down the line. You want to delegate most of the work to the database instead of R. By having them under different schemas in the same database, you can easily do cross schema queries. At the moment, you would have to use postgres_fdw to achieve less efficient but similar results. There are no benefits to having multiple databases since they are all hosted on the same machine and have the same user permissions.

That's basically it. But, you know, it works this way too.

https://www.postgresql.org/docs/current/ddl-schemas.html

**Comment by kdaust** [comment]
Gonna put this on the backburner for now...
