### ISSUE TITLE
Help with DB

### ISSUE THREAD

**Issue by kdaust** [FLNRO-Smithers-Research/CCISS_ShinyApp_v12#24]
Hey @meztez - hoping to get some advice/help from you on postgresql. So, there's the table cciss_future12, which has all the bgc predictions (and very big table; 260 entries for each siteref). Some of the BGC mapping has changed recently, so I would like to update the bgc column. I did a spatial join with an updated BGC map and the centre points to create the table bgc_attribution, which has columns siteno and bgc (and an index on siteno). My plan was to join the table and populate a new column in cciss_future12 with the updates:

`UPDATE cciss_future12
SET bgc_new = bgc_attribution.bgc
FROM bgc_attribution
WHERE cciss_future12.siteno = bgc_attribution.siteno;`

Unfortunately, it always seems to use up the disk space and then fail. This morning, I started with ~150 Gb free space, and after about 6 hours, it used it all up and stopped. Do you have any suggestions for how to do this in a more space efficient way? I know it's a big table, but just adding 1 column doesn't seem like it should be such a big deal...

Many thanks!

**Comment by meztez** [comment]
Some notes

Another thing I find useful when doing these kinds of operation is using a sample of the larger target table to test my query.

If bgc_attribution is much smaller than cciss_future12 and you are duplicating information, the merge should happen when you retrieve subsets of rows from cciss_future12  then add bgc_attribution at run time.

I do know the type of bgc, but it might be more efficient to deal with a bgc id instead of a UTF-8 varchar. IDs can get pretty compact memory footprint.

**Comment by meztez** [comment]
Depends, if you are able, drop and restore cciss_future12. Rebuild table index.
Or cross fingers and wait for tomorrow.
![image](https://user-images.githubusercontent.com/31039074/138017237-437411de-e2e6-48b7-8b98-4a3b7bbdb30d.png)

**Comment by kdaust** [comment]
Ok thanks. Remaking would probably be a good idea. Even making the index takes more than a day though...

thanks, but v12 is quite difference. Would you suggest doing a pg_dump of the table, dropping, and restoring from that?

**Comment by meztez** [comment]
I'm checked pg_stat_activity;

`SELECT * FROM pg_stat_activity;`

The only remaining active query is the vacuum.

You can stop it using if you wish. 

`SELECT * FROM pg_terminate_backend(pid)`

Another thing. The table reads about 2.3 billions rows by sequential scan. Does it make sense to you?

```
> dt <- setDT(dbGetQuery(conn, " SELECT * FROM pg_stat_user_tables WHERE relname='cciss_future12';
+ "))
> dt
    relid schemaname        relname seq_scan seq_tup_read idx_scan
1: 412697     public cciss_future12        3   2345147699        3
   idx_tup_fetch n_tup_ins n_tup_upd n_tup_del n_tup_hot_upd n_live_tup
1:           777         0         0         0             0          0
   n_dead_tup n_mod_since_analyze last_vacuum last_autovacuum last_analyze
1:          0                   0        <NA>            <NA>         <NA>
   last_autoanalyze vacuum_count autovacuum_count analyze_count
1:             <NA>            0                0             0
   autoanalyze_count
1:                 0
```
https://www.postgresql.org/docs/9.2/monitoring-stats.html

**Comment by kdaust** [comment]
Yep I think 2.3 billion sounds about right - there are ~ 6842000 sites, and each of them has 260 rows (13 gcms, 5 periods, 4 carbon scenarios). And then I know I accidentally have some duplicates (I've been meaning to deal with them but doing anything to the table takes so long I've been putting it off).
