### ISSUE TITLE
Data.table .() notation

### ISSUE THREAD

**Issue by kdaust** [FLNRO-Smithers-Research/CCISS_ShinyApp_v12#25]
@meztez - quick question: in data.table I usually use .() as a shortcut for list() (e.g. `dt[,.(colnames),.(grouping vars)]. I noticed you changed most of these to list(). Why is this preferable (it doesn't bother me at all, but I'm doing some more updates and was wondering whether I should get used to using list() too)?

**Comment by meztez** [comment]
Readability, pass package checks without undefined function "." as this is only defined within the "[.data.table" function.

Since I tend to copy code a lot, sometimes I turn a data.table call into a direct set and .( cannot be used there.

No hard particular reason beside that. It is fine to use.

**Comment by kdaust** [comment]
Ok, that all makes sense, thanks! I absolutely love data.table, such an amazing addition to the R ecosystem
