### ISSUE TITLE
Error in library(ccissdev)

### ISSUE THREAD

**Issue by dewikiswani** [FLNRO-Smithers-Research/CCISS_ShinyApp_v12#26]
I have done these steps:
`remotes::install_github("bcgov/CCISS_ShinyApp")`

but if I hit the Run App (whether it's on the global.R, server.R, or ui.R files) then an error appears as follows:
![image](https://user-images.githubusercontent.com/38982948/143187024-17e6554b-7b83-4e2e-a142-64613170bf99.png)

what solution should be done if an error appears as above

**Comment by kdaust** [comment]
The R package is tied to the app, so if you're using the CCISS_ShinyApp_v12, you also need to use that package, e.g. `install_github("FLNRO-Smithers-Research/CCISS_ShinyApp_v12")` which will install the ccissdev package.
